name: Branch Policy

on:
  pull_request:
    branches:
      - main

jobs:
  validate-source-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Validate source branch
        run: |
          if [ "${{ github.head_ref }}" != "staging" ]; then
            echo "Only staging can create a PR into main."
            exit 1
          fi

          echo "Valid source branch: staging"