name: Main Branch Policy

on:
  pull_request:
    branches:
      - main

jobs:
  source-branch-check:
    name: staging-only
    runs-on: ubuntu-latest

    steps:
      - name: Check source branch
        run: |
          if [ "${{ github.head_ref }}" != "staging" ]; then
            echo "Only the staging branch can merge into main."
            exit 1
          fi

<<<<<<< HEAD
          echo "Source branch is staging."
#heheh
=======

          echo "Source branch is staging."
#new staging
#hehehe
#youuu


>>>>>>> 4ca4b35b0104f740ecb2a351e09b39aee7f7e858
